### PR TITLE
Update README to specify packages required on Ubuntu

### PR DESCRIPTION
**Pull request by mosic**
I had the same issue mentioned in https://github.com/nimgl/nimgl/issues/14, and either installing `xorg-dev` or individual libraries (`libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev`) got the example code to successfully build.

I don't have access to a Windows & macOS machines right now so I can't test the build on those platforms, but it seems like a good idea to have a requirement list for all of the supported ones.

### CODE REVIEW

**Comment by lmariscal** [comment]
Thanks, I will create a CI test with github actions to further test the requirements before adding them to the README.

**Comment by mosic** [comment]
That's even better, thanks for taking care of it!

**Comment by kraptor** [comment]
On Mint I had to install the following packages:

```xlibmesa-glu-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev```

**Comment by mosic** [comment]
Closing since the PR is outdated.

**Pull request closed without merging**
